favorite:
  # if no drink is specified, the configmap will generate a release name specific tea
  drink: ~
  # if no food is specified, the template should fail to render.
  food: ~

pizzaToppings:
  - sausage
  - pepperoni
