apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  food: {{required "[ERROR] .Values.favorite.food not specified - add to Values or pass with `--set` " .Values.favorite.food | quote }}
  {{- if eq .Values.favorite.food "pizza" }}
  toppings: |-
    {{- range .Values.pizzaToppings }}
    - {{ . | title | quote }}
    {{- end }}
  {{- end }}
  {{- $defaultDrink := (printf "%s-tea" (include "helm-sandbox.fullname" .)) }}
  drink:
    # Note that the default drink, if not specified
    # is set to {{ $defaultDrink }}
    type: {{ .Values.favorite.drink.type | default $defaultDrink | quote }}
    {{- if .Values.favorite.drink.type }}
    {{- with .Values.favorite.drink }}
      {{- if eq .type "coffee" }}
    cream: true
    sugar: false
      {{- else if eq .type "tea" }}
    cream: false
    sugar: true
      {{- end }}
    {{- end }}
    {{- end }}
