apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  {{- $baseIndent := 2 }}
  food: {{required "[ERROR] .Values.favorite.food not specified - add to Values or pass with `--set` " .Values.favorite.food | quote }}
  {{- if eq .Values.favorite.food "pizza" }}
  {{- $nestedIndent := (add $baseIndent 2 ) }}
  toppings: |-
    {{- range .Values.pizzaToppings }}
    - {{ . | title | quote }}
    {{- end }}
  baseIndent: {{ $baseIndent | quote }}
  nestedIndent: {{ $nestedIndent | quote }}
  {{- end }}
  {{- /* note you can use template comments to prevent rendering */}}
  {{- $defaultDrink := (printf "%s-tea" (include "helm-sandbox.fullname" .)) }}
  drink: {{ .Values.favorite.drink | default $defaultDrink | quote }}
  {{- if .Values.favorite.drink }}
  drinkDoctoring: |-
  {{- with .Values.favorite }}
    {{- if eq .drink "coffee" }}
    cream: true
    sugar: false
    {{- else if eq .drink "tea" }}
    cream: false
    sugar: true
    {{- else }}
    cream: false
    sugar: false
    {{- end }}
  {{- end }}
  {{- end }}
